services:
  camera:
    image: dockercam:0
    container_name: camcon
    ports:
      - "8000:8000"
    # 8554 for h264/rtsp
    # - "8554:8554"
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/gpiomem:/dev/gpiomem"
    group_add:
      - video
      - gpio
      # - "997" # if 997 is group gpio on the host
    volumes:
      - "/run/udev:/run/udev:ro"
      # - "/sys:/sys"
      - "/sys/class/gpio:/sys/class/gpio"
      - "/dev/mem:/dev/mem" # pigpio needs this
      - /home/pi/dockercam/app:/app
    restart: unless-stopped
