# Build stage of pigpio
FROM debian:bullseye

RUN apt-get update && apt-get install -y wget unzip build-essential
RUN wget https://github.com/joan2937/pigpio/archive/master.zip
RUN unzip master.zip
WORKDIR /pigpio-master
RUN make

COPY app/start.sh .

CMD ["/bin/bash", "start.sh"]